steps: 
- name: 'gcr.io/cloud-builders/go'
  args: ['install', 'hello']
  env: ['GOPATH=./go-hpa']

- id:  'Rodando teste unitário'  
  name: 'gcr.io/cloud-builders/go'
  args: ['test', 'hello']
  env: ['GOPATH=./go-hpa']

